version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
  celery-worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - redis
